services:
  open-choice:
    image: stephanevdb/open-choice
    restart: always
    ports:
      - "8737:8737"
    volumes:
      - ./open-choice:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8737/health"]
      interval: 30s
      timeout: 10s
      retries: 3
